// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bplkugmjpvxivrjulrmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbGt1Z21qcHZ4aXZyanVscm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDIxMjcsImV4cCI6MjA3MDA3ODEyN30.5jEpcQitX2UCW0qcDFiGMLle0StVW0p9VeIkmYsp92I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});